ScriptAlias /mai "/var/www/my/mai"
<Directory "/var/www/my/mai">
    Options Indexes FollowSymLinks ExecCGI
    AllowOverride All
#    order allow,deny
    Require all granted
</Directory>

#RewriteEngine On
#RewriteRule ^/maiex/guld/newHres$ http://192.168.179.17:3000/mai/guld/newHres [L,R]

#ProxyRequest Off
#ProxyPass /maiex http://192.168.179.17:3000/mai
#ProxyPassReverse /maiex http://192.168.179.17:3000/mai

Listen 8080
<VirtualHost *:8080>

    ProxyPreserveHost On

    ProxyPass / http://192.168.179.17:3000/
    ProxyPassReverse / http://192.168.179.17:3000/
</VirtualHost>
